name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Deploy to cPanel
        uses: appleboy/scp-action@v0.3.0
        with:
          host:  www.dev.ptechfusion.com
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          source: ".next/"  # Update this line to point to the correct build directory

